name: Build & Deploy app

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  login:
    runs-on: ubuntu-latest
    container:
      image: "docker:19.03.8"
    steps:
      - uses: actions/checkout@v2
      - name: Login 
        run: |
          docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.GH_TOKEN }}
          docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/todo_app:latest || true
          docker build --cache-from docker.pkg.github.com/$GITHUB_REPOSITORY/todo_app:latest --tag docker.pkg.github.com/$GITHUB_REPOSITORY/todo_app:${GITHUB_SHA::8} --tag $GITHUB_REPOSITORY:latest .
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/todo_app:${GITHUB_SHA::8}
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/todo_app:latest