name: Build & Deploy app

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  login:
    runs-on: ubuntu-latest
    container:
      image: "docker:19.03.8"
    steps:
      - uses: actions/checkout@v2
      - name: Login 
        run: |
          docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.GH_TOKEN }}
          docker pull $GITHUB_REPOSITORY:latest || true
          docker build --cache-from $GITHUB_REPOSITORY:latest --tag $GITHUB_REPOSITORY:${GITHUB_SHA::8} --tag $GITHUB_REPOSITORY:latest .
          docker push $GITHUB_ACTOR/$GITHUB_REPOSITORY:${GITHUB_SHA::8}
          docker push $GITHUB_ACTOR/$GITHUB_REPOSITORY:latest